# fly.toml app configuration file generated for comp7940-lab5-23473355 on 2024-03-04T21:29:27+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[[vm]]
  size = 'shared-cpu-1x'

app = 'comp7940-lab5-23473355'
primary_region = 'nrt'

[build]
builder = 'paketobuildpacks/builder:base'

[env]
PORT = '8080'

[[services]]
internal_port = 8000
protocol = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[vm]]
size = 'shared-cpu-1x'